/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apostador;
import java.util.ArrayList;
/**
 *
 * @author DiegoCarrascal
 */
public class NewJFrame extends javax.swing.JFrame {


    private float X, Y, Z,TOTAL;
    private Solucion mi_max = new Solucion(0, 0, 0);
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        XInput = new javax.swing.JTextField();
        YInput = new javax.swing.JTextField();
        ZInput = new javax.swing.JTextField();
        TOTALInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RTA = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        Boton = new javax.swing.JButton();
        max_check = new javax.swing.JCheckBox();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Apostador"));

        jLabel1.setText("X: Victoria");

        jLabel2.setText("Y: Empate");

        jLabel3.setText("Z: Perdida");

        XInput.setText("2.3");
        XInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XInputActionPerformed(evt);
            }
        });

        YInput.setText("3.4");
        YInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YInputActionPerformed(evt);
            }
        });

        ZInput.setText("12");
        ZInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZInputActionPerformed(evt);
            }
        });

        TOTALInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTALInputActionPerformed(evt);
            }
        });

        jLabel4.setText("Total apostar");

        RTA.setColumns(20);
        RTA.setRows(5);
        jScrollPane1.setViewportView(RTA);

        jLabel5.setText("Resultado:");

        Boton.setText("Jugar");
        Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActionPerformed(evt);
            }
        });

        max_check.setText("Max result");
        max_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                max_checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(XInput, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(YInput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ZInput)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TOTALInput)
                                    .addComponent(Boton, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                                .addGap(34, 34, 34))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(max_check)
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(XInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(YInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TOTALInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ZInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Boton)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(max_check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XInputActionPerformed

    private void TOTALInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTALInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TOTALInputActionPerformed

    private void BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActionPerformed

        this.X = Float.valueOf(this.XInput.getText());
        this.Y = Float.valueOf(this.YInput.getText());
        this.Z = Float.valueOf(this.ZInput.getText());
        this.TOTAL = Float.valueOf(this.TOTALInput.getText());
        this.RTA.setText(this.solucionar());
    }//GEN-LAST:event_BotonActionPerformed

    private void YInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YInputActionPerformed

    private void ZInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZInputActionPerformed

    private void max_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_max_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_max_checkActionPerformed
   
    private String solucionar() {
       ArrayList<Solucion> g = permutador();
       String rta = "Su apuesta debe ser: \n";
       if(max_check.isSelected()){
           return rta + mi_max.toString2(X, Y, Z);
       }else{
           rta = g.stream().map((solucion) -> solucion.toString2(X,Y,Z)+"\n").reduce(rta, String::concat);
       }
       
       return rta;
    }

    public ArrayList<Solucion> permutador(){
        ArrayList<Solucion> s = new ArrayList<>();
        float a = 0;
        while(a <= TOTAL){
           float b = 0;
           while(a + b <= TOTAL){
               float c = 0;
               while(a + b + c <= TOTAL){
                   if(a + b + c == TOTAL){
                    if(isValida(a, b, c)){                           
                        Solucion ss = new Solucion(a, b, c);                          
                        set_mayor(ss);
                        s.add(ss);
                    }
                   }
                   c = c + 50;
               }
               b = b + 50;
           }
            a = a + 50;
        }
        return s;
    }    
    
    private void set_mayor(Solucion nueva){
        if(nueva.get_max(X, Y, Z) > mi_max.get_max(X, Y, Z)){
            mi_max = nueva;
        }
    }
    
    public ArrayList<Solucion> permutador2(){
        ArrayList<Solucion> s = new ArrayList<>();
        float a = 0;
        while(a <= TOTAL){
           float b = 0;
           while(a + b <= TOTAL){
               float c = TOTAL;
               while(a + b + c <= TOTAL){
                   if(isValida(a, b, c)){         
                     //  if(mi)
                       s.add(new Solucion(a, b, c));
                   }
                   c = c - 50;
                   b = b + 50;
               }
               b = b + 50;
           }
            a = a + 50;
        }
        return s;
    }
    private boolean isValida(float a, float b, float c){
        return a*X >= TOTAL && b*Y >= TOTAL && c*Z >= TOTAL;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton;
    private javax.swing.JTextArea RTA;
    private javax.swing.JTextField TOTALInput;
    private javax.swing.JTextField XInput;
    private javax.swing.JTextField YInput;
    private javax.swing.JTextField ZInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox max_check;
    // End of variables declaration//GEN-END:variables

}
